Nextgen ready? Only ollama done so far.

diff --git a/apps/Utility/ollama.yaml b/apps/Utility/ollama.yaml
--- a/apps/Utility/ollama.yaml
+++ b/apps/Utility/ollama.yaml
@@ -35,6 +35,11 @@ services:
 
     image: "cdc-u24"
 
+    #entrypoint: ["bash", "-c", "trap 'exit 0' TERM; bash -c \"$$(printf \"%s\\n\" \"$@\")\"; while true; do sleep 1; done", "--"]
+    entrypoint: ["/bin/tini", "/bin/bash", "--", "-c", "$$(printf \"%s\\n\" \"$@\"); sleep infinity"]
+
+    network: none
+
     working_dir: /home/${USER}
     user: "${USER}"
 
@@ -57,7 +62,7 @@ services:
     shm_size: "1G"
 
     volumes: &common-volumes
-      - "${COMPOSE_PATH?Setting COMPOSE_PATH is required.}/home:/home/${USER}:rw"
+      - "${CDC_APP_PATH}/home:/home/${USER}:rw"
 
     devices:
       - "/dev/dri:/dev/dri"
@@ -72,116 +77,118 @@ services:
   download:
     <<: *common
 
-    x-launch-script: &download_script
-      - echo "DOWNLOAD"
-      - mkdir -p Downloads
-      - VERSION="$$(curl -s https://api.github.com/repos/ollama/ollama/releases/latest | jq --raw-output '.name')"
-      - LATESTURL="$$(curl -s https://api.github.com/repos/ollama/ollama/releases/latest | jq --raw-output '.assets[] | .browser_download_url' | grep ollama-linux-amd64.tgz)"
-      - LATESTFILENAME="ollama-linux-amd64-$$VERSION.tgz"
-      - |
-        if [ ! -e "Downloads/$$LATESTFILENAME" ]; then
-          curl -L -o "Downloads/$$LATESTFILENAME" "$$LATESTURL"
-        fi
-      - ln -sf "$$LATESTFILENAME" Downloads/ollama-linux-amd64-latest.tgz
+    network_mode: bridge
+
+    x-application:
+      launch-script: &download_script
+        - echo "DOWNLOAD"
+        - mkdir -p Downloads
+        - VERSION="$$(curl -s https://api.github.com/repos/ollama/ollama/releases/latest | jq --raw-output '.name')"
+        - LATESTURL="$$(curl -s https://api.github.com/repos/ollama/ollama/releases/latest | jq --raw-output '.assets[] | .browser_download_url' | grep ollama-linux-amd64.tgz)"
+        - LATESTFILENAME="ollama-linux-amd64-$$VERSION.tgz"
+        - |
+          if [ ! -e "Downloads/$$LATESTFILENAME" ]; then
+            curl -L -o "Downloads/$$LATESTFILENAME" "$$LATESTURL"
+          fi
+        - ln -sf "$$LATESTFILENAME" Downloads/ollama-linux-amd64-latest.tgz
 
   redownload:
     <<: *common
 
-    x-launch-script: &redownload_script
-      - echo "REDOWNLOAD"
-      - mkdir -p Downloads
-      - VERSION="$$(curl -s https://api.github.com/repos/ollama/ollama/releases/latest | jq --raw-output '.name')"
-      - LATESTURL="$$(curl -s https://api.github.com/repos/ollama/ollama/releases/latest | jq --raw-output '.assets[] | .browser_download_url' | grep ollama-linux-amd64.tgz)"
-      - LATESTFILENAME="ollama-linux-amd64-$$VERSION.tgz"
-      - rm -rf "Downloads/$$LATESTFILENAME" Downloads/ollama-linux-amd64-latest.tgz
-      - *download_script
+    network_mode: bridge
+
+    x-application:
+      launch-script: &redownload_script
+        - echo "REDOWNLOAD"
+        - mkdir -p Downloads
+        - VERSION="$$(curl -s https://api.github.com/repos/ollama/ollama/releases/latest | jq --raw-output '.name')"
+        - LATESTURL="$$(curl -s https://api.github.com/repos/ollama/ollama/releases/latest | jq --raw-output '.assets[] | .browser_download_url' | grep ollama-linux-amd64.tgz)"
+        - LATESTFILENAME="ollama-linux-amd64-$$VERSION.tgz"
+        - rm -rf "Downloads/$$LATESTFILENAME" Downloads/ollama-linux-amd64-latest.tgz
+        - *download_script
 
   install:
     <<: *common
 
-    x-launch-script: &install_script
-      - VERSION="$${1:-ollama-linux-amd64-latest.tgz}";
-      - echo "INSTALL $$VERSION"; 
-      - |
-        if [ ! -e ~/.local/share/ollama ]; then
-          mkdir -p ~/.local/share/ollama
-          cd ~/.local/share/ollama
-          tar -zxf ~/Downloads/"$$VERSION"
-        fi
+    x-application:
+      launch-script: &install_script
+        - VERSION="$${1:-ollama-linux-amd64-latest.tgz}";
+        - echo "INSTALL $$VERSION"; 
+        - |
+          if [ ! -e ~/.local/share/ollama ]; then
+            mkdir -p ~/.local/share/ollama
+            cd ~/.local/share/ollama
+            tar -zxf ~/Downloads/"$$VERSION"
+          fi
 
   reinstall:
     <<: *common
 
-    x-launch-script: &reinstall_script
-      - VERSION="$${1:-ollama-linux-amd64-latest.tgz}"
-      - echo "REINSTALL $$VERSION" 
-      - rm -rf ~/.local/share/ollama
-      - *install_script
+    network_mode: bridge
+
+    x-application:
+      launch-script: &reinstall_script
+        - VERSION="$${1:-ollama-linux-amd64-latest.tgz}"
+        - echo "REINSTALL $$VERSION" 
+        - rm -rf ~/.local/share/ollama
+        - *install_script
 
   ## UPDATE ##
 
   update-check:
     <<: *common
 
-    command:
-      - echo "UPDATE CHECK"
-      - VERSION="$$(curl -s https://api.github.com/repos/ollama/ollama/releases/latest | jq --raw-output)"
-      - LATESTFILENAME="ollama-linux-amd64-$$VERSION.tgz"
-      - mkdir -p Downloads
-      - if [ -e "Downloads/$$LATESTFILENAME" ]; then
-          echo "No new version";
-          exit 0;
-        fi
-      - echo "File missing, or server-side file newer"
-      - exit 1
+    network_mode: bridge
+
+    x-application:
+      launch-script:
+        - echo "UPDATE CHECK"
+        - VERSION="$$(curl -s https://api.github.com/repos/ollama/ollama/releases/latest | jq --raw-output)"
+        - LATESTFILENAME="ollama-linux-amd64-$$VERSION.tgz"
+        - mkdir -p Downloads
+        - if [ -e "Downloads/$$LATESTFILENAME" ]; then
+            echo "No new version";
+            exit 0;
+          fi
+        - echo "File missing, or server-side file newer"
+        - exit 1
 
   update:
     <<: *common
 
-    x-launch-script:
-      - echo "UPDATE"
-      - *redownload_script
-      - *reinstall_script
+    network_mode: bridge
+
+    x-application:
+      launch-script:
+        - echo "UPDATE"
+        - *redownload_script
+        - *reinstall_script
 
   ## EXECUTE ###
 
   ollama-serve:
     <<: *common
 
+    network_mode: bridge
+
     ports:
-      - "11434"
-
-    command:
-      - echo "ollama-serve"
-      - printf "+%s+\n" "$@"
-      #- OLLAMA_HOST=0.0.0.0:11434 ~/.local/share/ollama/bin/ollama serve
-
-    environment:
-      <<: *common-env
-      CDC_LAUNCH_ARGS: "\"test me\" more"
-    
-
-    entrypoint:
-      - "/home/$USER/cdc-launch"
-
-    stdin_open: true
-    tty: true
+      - "11434:11434"
 
     x-application:
-      container_name: cdc_ollama_ollama
-      interactive: true
+      launch-script:
+        - echo "ollama-serve"
+        - OLLAMA_HOST=0.0.0.0:11434 ~/.local/share/ollama/bin/ollama serve
+      features:
+        - GPU
 
   ollama:
     <<: *common
 
-    x-launch-script:
-      - echo "ollama"
-      - ~/.local/share/ollama/bin/ollama "$@"
-
     x-application:
-      container_name: cdc_ollama_ollama
-      interactive: true
-
+      use_service: ollama-serve
+      launch-script:
+        - echo "ollama"
+        - ~/.local/share/ollama/bin/ollama "$@"
 
   ## INTERACTIVE ##
 
@@ -189,9 +196,10 @@ services:
     <<: *common
 
     x-application:
-      container_name: cdc_ollama_ollama
+      use_service: ollama-serve
       interactive: true
 
-    x-launch-script:
-      - echo "INTERACTIVE"
-      - bash
+      launch-script:
+        - echo "INTERACTIVE"
+        - bash
+
