Updates to format, add blender support

diff --git a/apps/Network/discord.yaml b/apps/Network/discord.yaml
--- a/apps/Network/discord.yaml
+++ b/apps/Network/discord.yaml
@@ -14,12 +14,135 @@ x-application:
   config-default: |
     version: "3.8"
 
+  env-default: |
     # This container has no configurable options
 
-  launchers:
+services:
 
-    discord:
+  ## COMMON PART ##
 
+  common: &common
+
+    image: "desktop-container-default"
+
+    working_dir: /home/$USER
+    hostname: "discord_container"
+    user: "${USER}"
+
+    environment: &common-env
+      LANG: "${LANG}"
+      XDG_RUNTIME_DIR: "${XDG_RUNTIME_DIR}"
+      XDG_DATA_DIRS: "${XDG_DATA_DIRS}"
+      XDG_CURRENT_DESKTOP: "GNOME"
+      BROWSER: "falkon"
+      DISPLAY: "${DISPLAY}"
+      XAUTHORITY: "${XAUTHORITY}"
+
+    cap_drop:
+      - ALL
+    cap_add:
+      - SYS_CHROOT
+
+    security_opt:
+      - no-new-privileges
+
+    read_only: true
+    tmpfs:
+      - /tmp
+      - /run
+
+    shm_size: "512m"
+
+    volumes: &common-volumes
+      - "${CDC_HOME}/home:/home/${USER}:rw"
+      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
+      - "${XAUTHORITY}:${XAUTHORITY}:rw"
+      - "${XDG_RUNTIME_DIR}/pipewire-0:/tmp/${USER}/run/pipewire-0:rw"
+      - "${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:/tmp/${USER}/run/${WAYLAND_DISPLAY}:ro"
+      
+    devices:
+      - "/dev/dri:/dev/dri"
+      - "/dev/snd:/dev/snd"
+
+    security_opt:
+      - no-new-privileges
+
+    userns_mode: "keep-id"
+
+
+  ## INSTALL ##
+  
+  install-prepare: &install-prepare
+    <<: *common
+
+    environment:
+      <<: *common-env
+
+    command: 
+      - echo "INSTALL PREPARE"
+      - mkdir -p files
+      - curl -L -o files/discord.tar.gz "https://discordapp.com/api/download?platform=linux&format=tar.gz"
+
+
+  install: &install
+    <<: *common 
+
+    command: 
+      - echo "INSTALL"
+      - rm -rf ~/discord &&
+        mkdir ~/discord &&
+        cd ~/discord &&
+        tar -xf ~/files/discord.tar.gz &&
+        mkdir -p ~/.local/share/applications &&
+        cp Discord/discord.desktop ~/.local/share/applications/discord.desktop &&
+        sed -i 's%/usr/share/discord/Discord%/home/$USER/discord/Discord/Discord%' ~/.local/share/applications/discord.desktop
+
+  ## UPDATE ##
+
+  update-check: &update-check
+    <<: *common 
+
+    command: 
+      - echo "UPDATE CHECK"
+      - mkdir -p files
+      - if [ -e files/discord.tar.gz ]; then
+          LASTMOD_LINE="$$(curl -sI -L "https://discordapp.com/api/download?platform=linux&format=tar.gz" | grep -i '^Last-Modified:' | cut "-d:" -f2- | sed 's/^\s*\|\s$$//g')";
+          if [ -z "$$LASTMOD_LINE" ]; then
+            echo "Could not get last modified date";
+            exit 0;
+          fi;
+          REMOTE_TS="$$(date -d "$${LASTMOD_LINE}" +%s)";
+          LOCAL_TS="$$(date -r "files/discord.tar.gz" +%s)";
+          if [ "$$REMOTE_TS" -lt "$$LOCAL_TS" ]; then
+            echo "No new version";
+            exit 0;
+          fi;
+        fi
+      - echo "File missing, or server-side file newer"
+      - exit 1 
+
+  update-prepare: &update-prepare
+    <<: *install-prepare   
+
+  update: &update
+    <<: *install 
+
+
+  ## EXECUTE ###
+
+  discord:
+    <<: *common
+
+    container_name: cdc_discord_discord
+
+    command: 
+      - echo "DISCORD"
+      - cd discord/Discord
+      - pipewire-pulse &
+      - exec ./Discord
+
+    x-launcher:
+    
       devices:
         - video
 
@@ -43,151 +166,11 @@ x-application:
             size: 256
             dest: discord.png
 
-services:
-
-  ## COMMON PART ##
-
-  common: &common
-
-    working_dir: /home/$USER
-    hostname: "discord_container"
-    user: "${USER}"
-
-    environment: &common-env
-      LANG: "${LANG}"
-      XDG_RUNTIME_DIR: "${XDG_RUNTIME_DIR}"
-      XDG_DATA_DIRS: "${XDG_DATA_DIRS}"
-      XDG_CURRENT_DESKTOP: "GNOME"
-      BROWSER: "falkon"
-      DISPLAY: "${DISPLAY}"
-      XAUTHORITY: "${XAUTHORITY}"
-      
-      #DBUS_SESSION_BUS_ADDRESS: "unix:path=/tmp/${USER}/run/bus"
-
-    cap_drop:
-      - ALL
-    cap_add:
-      - SYS_CHROOT
-
-    security_opt:
-      - no-new-privileges
-
-    read_only: true
-    tmpfs:
-      - /tmp
-      - /run
-
-    shm_size: "512m"
-
-    volumes: &common-volumes
-      - "${COMPOSE_APP_HOME}/home:/home/${USER}:rw"
-      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
-      - "${XAUTHORITY}:${XAUTHORITY}:rw"
-      - "${XDG_RUNTIME_DIR}/pipewire-0:/tmp/${USER}/run/pipewire-0:rw"
-      - "${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:/tmp/${USER}/run/${WAYLAND_DISPLAY}:ro"
-      
-    # - "${COMPOSE_APP_DBUS_PATH}:/tmp/${USER}/run/bus:rw"
-
-    devices:
-      - "/dev/dri:/dev/dri"
-      - "/dev/snd:/dev/snd"
-
-    security_opt:
-      - "label=disable"
-
-    userns_mode: "keep-id"
-
-
-  ## INSTALL ##
-  
-  install-prepare: &install-prepare
-    <<: *common
-
-    image: "desktop-container-default"
-
-    environment:
-      <<: *common-env
-
-      LAUNCH_COMMAND: >
-        echo "INSTALL PREPARE";
-        mkdir -p files;
-        curl -L -o files/discord.tar.gz "https://discordapp.com/api/download?platform=linux&format=tar.gz"
-
-  install: &install
-    <<: *common 
-
-    image: "desktop-container-default"
-
-    environment:
-      <<: *common-env
-      LAUNCH_COMMAND: >
-        echo "INSTALL";
-        rm -rf ~/discord &&
-        mkdir ~/discord &&
-        cd ~/discord &&
-        tar -xf ~/files/discord.tar.gz &&
-        mkdir -p ~/.local/share/applications &&
-        cp Discord/discord.desktop ~/.local/share/applications/discord.desktop &&
-        sed -i 's%/usr/share/discord/Discord%/home/$USER/discord/Discord/Discord%'  ~/.local/share/applications/discord.desktop
-
-  ## UPDATE ##
-
-  update-check: &update-check
-    <<: *common 
-
-    image: "desktop-container-default"
-
-    environment:
-      <<: *common-env
-      LAUNCH_COMMAND: >
-        echo "UPDATE CHECK";
-        mkdir -p files;
-        if [ -e files/discord.tar.gz ]; then
-          LASTMOD_LINE="$$(curl -sI -L "https://discordapp.com/api/download?platform=linux&format=tar.gz" | grep -i '^Last-Modified:' | cut "-d:" -f2- | sed 's/^\s*\|\s$//g')";
-          if [ -z "$$LASTMOD_LINE" ]; then
-            echo "Could not get last modified date";
-            exit 0;
-          fi;
-          REMOTE_TS="$$(date -d "$${LASTMOD_LINE}" +%s)";
-          LOCAL_TS="$$(date -r "files/discord.tar.gz" +%s)";
-          if [ "$$REMOTE_TS" -lt "$$LOCAL_TS" ];
-            then echo "No new version";
-            exit 0;
-          fi;
-        fi;
-        echo "File missing, or server-side file newer";
-        exit 1 
-
-  update-prepare: &update-prepare
-    <<: *install-prepare   
-
-  update: &update
-    <<: *install 
-
-
-  ## EXECUTE ###
-
-  discord:
-    <<: *common
-
-    container_name: htdc_discord_discord
-    image: "desktop-container-default"
-
-    environment:
-      <<: *common-env
-      LAUNCH_COMMAND: >
-        echo "DISCORD";
-        cd discord/Discord;
-        pipewire-pulse &
-        exec ./Discord
-
   ## INTERACTIVE ##
 
   interactive:
     <<: *common
 
-    image: "desktop-container-default"
-
-    environment:
-      <<: *common-env
-      LAUNCH_COMMAND: echo "INTERACTIVE"; bash
+    command: 
+      - echo "INTERACTIVE"
+      - bash
diff --git a/apps/Network/zoom.yaml b/apps/Network/zoom.yaml
--- a/apps/Network/zoom.yaml
+++ b/apps/Network/zoom.yaml
@@ -14,14 +14,159 @@ x-application:
     Use together with legacy-screenshare-helper (https://github.com/httk/legacy-screenshare-helper)
     to support screensharing.
 
-  config-default: |
+  override-default: |
     version: "3.8"
-    
-    # This container has no configurable options
 
-  launchers:
+    # Comment out as desired below to give zoom access to dbus session and/or system bus
+    #
+    #services:
+    #  zoom:
+    #    volumes:
+    #      - "${CDC_DBUS_PATH}:/tmp/${USER}/run/bus:rw"
+    #      - "${CDC_DBUS_SYSTEM_BUS_PATH}:/run/dbus/system_bus_socket:rw"
+    #    environment:
+    #      DBUS_SESSION_BUS_ADDRESS: "unix:path=/tmp/${USER}/run/bus"
+    #      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/run/dbus/system_bus_socket"
+    #    x-launcher:
+    #      dbus-proxy: --filter
+    #      dbus-system-proxy: --filter
+    #
 
-    zoom:
+  env-default: |
+    # No configurable options
+
+
+services:
+
+  ## COMMON PART ##
+
+  common: &common
+
+    image: "desktop-container-default"
+
+    working_dir: /home/$USER
+    hostname: "zoom_container"
+    user: "${USER}"
+
+    environment: &common-env
+      LANG: "${LANG}"
+      XDG_RUNTIME_DIR: "${XDG_RUNTIME_DIR}"
+      XDG_DATA_DIRS: "${XDG_DATA_DIRS}"
+      XDG_CURRENT_DESKTOP: "GNOME"
+      BROWSER: "falkon"
+      TERM: "xterm"
+      XTERM_LOCALE: "en_US.UTF-8"
+      XTERM_SHELL: "/usr/bin/bash"
+      DISPLAY: "${DISPLAY}"
+      XAUTHORITY: "${XAUTHORITY}"
+
+    cap_drop:
+      - ALL
+    cap_add:
+      - SYS_CHROOT
+
+    security_opt:
+      - no-new-privileges
+
+    read_only: true
+    tmpfs:
+      - /tmp
+      - /run
+
+    shm_size: "512m"
+
+    volumes: &common-volumes
+      - "${CDC_HOME}/home:/home/${USER}:rw"
+      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
+      - "${XAUTHORITY}:${XAUTHORITY}:rw"
+      - "${XDG_RUNTIME_DIR}/pipewire-0:/tmp/${USER}/run/pipewire-0:rw"
+
+    devices:
+      - "/dev/dri:/dev/dri"
+      - "/dev/snd:/dev/snd"
+
+    security_opt:
+      - "label=disable"
+
+    userns_mode: "keep-id"
+
+
+  ## INSTALL ##
+  
+  install-prepare: &install-prepare
+    <<: *common
+
+    # Note: the deb archive is needed just to get the icon, which does not seem to be included in the standalone install (?)
+    command:
+      - echo "INSTALL PREPARE"
+      - mkdir -p files
+      - curl -L -o files/zoom_x86_64.tar.xz "https://zoom.us/client/latest/zoom_x86_64.tar.xz"
+      - curl -L -o files/zoom_amd64.deb "https://zoom.us/client/latest/zoom_amd64.deb"
+
+  install: &install
+    <<: *common 
+
+    command:
+      - echo "INSTALL"
+      - rm -rf ~/zoom &&
+        mkdir ~/zoom &&
+        cd ~/zoom &&
+        mkdir tmp &&
+        cd tmp &&
+        ar x ~/files/zoom_amd64.deb &&
+        tar -xf data.tar.xz &&
+        cp ./usr/share/pixmaps/Zoom.png ../. &&
+        cd .. && rm -rf tmp &&
+        tar -xf ~/files/zoom_x86_64.tar.xz &&
+        mkdir -p ~/.local/share/applications &&
+        echo -e "[Desktop Entry]\nName=ZoomLauncher\nComment=Zoom Video Conference\nExec=/home/$${USER}/zoom/zoom/ZoomLauncher %U\nTerminal=false\nType=Application\nEncoding=UTF-8\nCategories=Network;Application;\nMimeType=x-scheme-handler/zoommtg;x-scheme-handler/zoomus;x-scheme-handler/tel;x-scheme-handler/callto;x-scheme-handler/zoomphonecall;\nX-KDE-Protocols=zoommtg;zoomus;tel;callto;zoomphonecall\nName[en_US]=ZoomLauncher" > ~/.local/share/applications/ZoomLauncher.desktop &&
+        update-desktop-database ~/.local/share/applications/
+
+  ## UPDATE ##
+
+  update-check: &update-check
+    <<: *common 
+
+    command: 
+      - echo "UPDATE CHECK"
+      - mkdir -p files
+      - if [ -e files/zoom_x86_64.tar.xz ]; then
+          LASTMOD_LINE="$$(curl -sI -L "https://zoom.us/client/latest/zoom_x86_64.tar.xz" | grep -i '^last-modified:' | cut "-d:" -f2- | sed 's/^\s*\|\s$$//g')";
+          if [ -z "$$LASTMOD_LINE" ]; then
+            echo "Could not get last modified date";
+            exit 0;
+          fi;
+          REMOTE_TS="$$(date -d "${LASTMOD_LINE}" +%s)";
+          LOCAL_TS="$$(date -r "files/zoom_x86_64.tar.xz" +%s)";
+          if [ "$$REMOTE_TS" -lt "$$LOCAL_TS" ]; then
+            echo "No new version";
+            exit 0;
+          fi;
+        fi;
+      - echo "File missing, or server-side file newer"
+      - exit 1 
+
+  update-prepare: &update-prepare
+    <<: *install-prepare   
+
+  update: &update
+    <<: *install 
+
+
+  ## EXECUTE ###
+
+  zoom:
+    <<: *common
+
+    container_name: cdc_zoom_zoom
+
+    command: 
+      - echo "ZOOM"
+      - cd zoom/zoom
+      - pipewire-pulse &
+      - LD_LIBRARY_PATH=/home/rar/zoom/zoom:/home/rar/zoom/zoom/Qt/lib exec ./zoom "$$@"
+
+    x-launcher:
 
       # zoom in x11 mode does not need dbus?
       #dbus-proxy: ""
@@ -50,161 +195,12 @@ x-application:
             size: 256
             dest: zoom.png
 
-services:
-
-  ## COMMON PART ##
-
-  common: &common
-
-    working_dir: /home/$USER
-    hostname: "zoom_container"
-    user: "${USER}"
-
-    environment: &common-env
-      LANG: "${LANG}"
-      XDG_RUNTIME_DIR: "${XDG_RUNTIME_DIR}"
-      XDG_DATA_DIRS: "${XDG_DATA_DIRS}"
-      XDG_CURRENT_DESKTOP: "GNOME"
-      BROWSER: "falkon"
-      TERM: "xterm"
-      XTERM_LOCALE: "en_US.UTF-8"
-      XTERM_SHELL: "/usr/bin/bash"
-      DISPLAY: "${DISPLAY}"
-      XAUTHORITY: "${XAUTHORITY}"
-      
-      #DBUS_SESSION_BUS_ADDRESS: "unix:path=/tmp/${USER}/run/bus"
-
-    cap_drop:
-      - ALL
-    cap_add:
-      - SYS_CHROOT
-
-    security_opt:
-      - no-new-privileges
-
-    read_only: true
-    tmpfs:
-      - /tmp
-      - /run
-
-    shm_size: "512m"
-
-    volumes: &common-volumes
-      - "${COMPOSE_APP_HOME}/home:/home/${USER}:rw"
-      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
-      - "${XAUTHORITY}:${XAUTHORITY}:rw"
-      - "${XDG_RUNTIME_DIR}/pipewire-0:/tmp/${USER}/run/pipewire-0:rw"
-
-    # - "${COMPOSE_APP_DBUS_PATH}:/tmp/${USER}/run/bus:rw"
-
-    devices:
-      - "/dev/dri:/dev/dri"
-      - "/dev/snd:/dev/snd"
-
-    security_opt:
-      - "label=disable"
-
-    userns_mode: "keep-id"
-
-
-  ## INSTALL ##
-  
-  install-prepare: &install-prepare
-    <<: *common
-
-    image: "desktop-container-default"
-
-    environment:
-      <<: *common-env
-
-      # Note: the deb archive is needed just to get the icon, which does not seem to be included in the standalone install (?)
-      LAUNCH_COMMAND: >
-        echo "INSTALL PREPARE";
-        mkdir -p files;
-        curl -L -o files/zoom_x86_64.tar.xz "https://zoom.us/client/latest/zoom_x86_64.tar.xz";
-        curl -L -o files/zoom_amd64.deb "https://zoom.us/client/latest/zoom_amd64.deb"
-
-  install: &install
-    <<: *common 
-
-    image: "desktop-container-default"
-
-    environment:
-      <<: *common-env
-      LAUNCH_COMMAND: >
-        echo "INSTALL";
-        rm -rf ~/zoom &&
-        mkdir ~/zoom &&
-        cd ~/zoom &&
-        mkdir tmp &&
-        cd tmp &&
-        ar x ~/files/zoom_amd64.deb &&
-        tar -xf data.tar.xz &&
-        cp ./usr/share/pixmaps/Zoom.png ../. &&
-        cd .. && rm -rf tmp &&
-        tar -xf ~/files/zoom_x86_64.tar.xz &&
-        mkdir -p ~/.local/share/applications &&
-        echo -e "[Desktop Entry]\nName=ZoomLauncher\nComment=Zoom Video Conference\nExec=/home/$USER/zoom/zoom/ZoomLauncher %U\nTerminal=false\nType=Application\nEncoding=UTF-8\nCategories=Network;Application;\nMimeType=x-scheme-handler/zoommtg;x-scheme-handler/zoomus;x-scheme-handler/tel;x-scheme-handler/callto;x-scheme-handler/zoomphonecall;\nX-KDE-Protocols=zoommtg;zoomus;tel;callto;zoomphonecall\nName[en_US]=ZoomLauncher" > ~/.local/share/applications/ZoomLauncher.desktop &&
-        update-desktop-database ~/.local/share/applications/
-
-  ## UPDATE ##
-
-  update-check: &update-check
-    <<: *common 
-
-    image: "desktop-container-default"
-
-    environment:
-      <<: *common-env
-      LAUNCH_COMMAND: >
-        echo "UPDATE CHECK";
-        mkdir -p files;
-        if [ -e files/zoom_x86_64.tar.xz ]; then
-          LASTMOD_LINE="$$(curl -sI -L "https://zoom.us/client/latest/zoom_x86_64.tar.xz" | grep -i '^Last-Modified:' | cut "-d:" -f2- | sed 's/^\s*\|\s$//g')";
-          if [ -z "$$LASTMOD_LINE" ]; then
-            echo "Could not get last modified date";
-            exit 0;
-          fi;
-          REMOTE_TS="$$(date -d "$${LASTMOD_LINE}" +%s)";
-          LOCAL_TS="$$(date -r "files/zoom_x86_64.tar.xz" +%s)";
-          if [ "$$REMOTE_TS" -lt "$$LOCAL_TS" ];
-            then echo "No new version";
-            exit 0;
-          fi;
-        fi;
-        echo "File missing, or server-side file newer";
-        exit 1 
-
-  update-prepare: &update-prepare
-    <<: *install-prepare   
-
-  update: &update
-    <<: *install 
-
-
-  ## EXECUTE ###
-
-  zoom:
-    <<: *common
-
-    container_name: htdc_zoom_zoom
-    image: "desktop-container-default"
-
-    environment:
-      <<: *common-env
-      LAUNCH_COMMAND: >
-        echo "ZOOM";
-        cd zoom/zoom;
-        pipewire-pulse &
-        LD_LIBRARY_PATH=/home/rar/zoom/zoom:/home/rar/zoom/zoom/Qt/lib exec ./zoom
 
   ## INTERACTIVE ##
 
   interactive:
     <<: *common
 
-    image: "desktop-container-default"
-
-    environment:
-      <<: *common-env
-      LAUNCH_COMMAND: echo "INTERACTIVE"; bash
+    command:
+      - echo "INTERACTIVE"
+      - bash
